# Generated by Django 5.0.7 on 2024-07-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
