# Generated by Django 5.0.7 on 2024-07-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='desc',
        ),
        migrations.AddField(
            model_name='user',
            name='second_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=10),
        ),
    ]
